/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyRatingsRouteImport } from './routes/my-ratings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as AccountPasswordRouteImport } from './routes/account.password'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminRatingsRouteImport } from './routes/admin/ratings'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner/analytics'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerRatingsRouteImport } from './routes/owner/ratings'
import { Route as OwnerStoreRouteImport } from './routes/owner/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRatingsRoute = MyRatingsRouteImport.update({
  id: '/my-ratings',
  path: '/my-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRatingsRoute = AdminRatingsRouteImport.update({
  id: '/admin/ratings',
  path: '/admin/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/owner/analytics',
  path: '/owner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRatingsRoute = OwnerRatingsRouteImport.update({
  id: '/owner/ratings',
  path: '/owner/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStoreRoute = OwnerStoreRouteImport.update({
  id: '/owner/store',
  path: '/owner/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-ratings': typeof MyRatingsRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/ratings': typeof OwnerRatingsRoute
  '/owner/store': typeof OwnerStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-ratings': typeof MyRatingsRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/ratings': typeof OwnerRatingsRoute
  '/owner/store': typeof OwnerStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-ratings': typeof MyRatingsRoute
  '/signup': typeof SignupRoute
  '/stores': typeof StoresRoute
  '/account/password': typeof AccountPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/ratings': typeof OwnerRatingsRoute
  '/owner/store': typeof OwnerStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-ratings'
    | '/signup'
    | '/stores'
    | '/account/password'
    | '/admin/dashboard'
    | '/admin/ratings'
    | '/admin/stores'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/dashboard'
    | '/owner/ratings'
    | '/owner/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-ratings'
    | '/signup'
    | '/stores'
    | '/account/password'
    | '/admin/dashboard'
    | '/admin/ratings'
    | '/admin/stores'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/dashboard'
    | '/owner/ratings'
    | '/owner/store'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-ratings'
    | '/signup'
    | '/stores'
    | '/account/password'
    | '/admin/dashboard'
    | '/admin/ratings'
    | '/admin/stores'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/dashboard'
    | '/owner/ratings'
    | '/owner/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyRatingsRoute: typeof MyRatingsRoute
  SignupRoute: typeof SignupRoute
  StoresRoute: typeof StoresRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRatingsRoute: typeof AdminRatingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerRatingsRoute: typeof OwnerRatingsRoute
  OwnerStoreRoute: typeof OwnerStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ratings': {
      id: '/my-ratings'
      path: '/my-ratings'
      fullPath: '/my-ratings'
      preLoaderRoute: typeof MyRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ratings': {
      id: '/admin/ratings'
      path: '/admin/ratings'
      fullPath: '/admin/ratings'
      preLoaderRoute: typeof AdminRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/ratings': {
      id: '/owner/ratings'
      path: '/owner/ratings'
      fullPath: '/owner/ratings'
      preLoaderRoute: typeof OwnerRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/store': {
      id: '/owner/store'
      path: '/owner/store'
      fullPath: '/owner/store'
      preLoaderRoute: typeof OwnerStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyRatingsRoute: MyRatingsRoute,
  SignupRoute: SignupRoute,
  StoresRoute: StoresRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRatingsRoute: AdminRatingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerRatingsRoute: OwnerRatingsRoute,
  OwnerStoreRoute: OwnerStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
